#define SYS_fork 1
#define SYS_exit 2
#define SYS_wait 3
#define SYS_pipe 4
#define SYS_read 5
#define SYS_kill 6
#define SYS_exec 7
#define SYS_fstat 8
#define SYS_chdir 9
#define SYS_dup 10
#define SYS_getpid 11
#define SYS_sbrk 12
#define SYS_sleep 13
#define SYS_uptime 14
#define SYS_open 15
#define SYS_write 16
#define SYS_mknod 17
#define SYS_unlink 18
#define SYS_link 19
#define SYS_mkdir 20
#define SYS_close 21
#define SYS_simple_arithmetic_syscall 22
#define SYS_make_duplicate 23
#define SYS_show_process_family 24
#define SYS_grep_syscall 25
#define SYS_set_priority_syscall 26
#define SYS_start_measure 27
#define SYS_end_measure 28
#define SYS_print_info 29
#define SYS_test_init_locks 30
#define SYS_test_sl_lock 31
#define SYS_test_sl_unlock 32
#define SYS_test_rw_read_lock 33
#define SYS_test_rw_read_unlock 34
#define SYS_test_rw_write_lock 35
#define SYS_test_rw_write_unlock 36
#define SYS_getlockstat 37
#define SYS_plock_acquire 38
#define SYS_plock_release 39
#define SYS_rw_reader_enter 40
#define SYS_rw_reader_exit  41
#define SYS_rw_writer_enter 42
#define SYS_rw_writer_exit  43