struct stat;
struct rtcdate;

int fork(void);
int exit(void) __attribute__((noreturn));
int wait(void);
int pipe(int*);
int write(int, const void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(const char*, int);
int mknod(const char*, short, short);
int unlink(const char*);
int fstat(int fd, struct stat*);
int link(const char*, const char*);
int mkdir(const char*);
int chdir(const char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);
int simple_arithmetic_syscall(int, int);
int make_duplicate(const char*);
int show_process_family(int);
int grep_syscall(const char*, const char*, char*, int);
int set_priority_syscall(int, int);
int start_measure(void);
int end_measure(void);
int print_info(void);
int test_init_locks(void);
int test_sl_lock(void);
int test_sl_unlock(void);
int test_rw_read_lock(void);
int test_rw_read_unlock(void);
int test_rw_write_lock(void);
int getlockstat(uint*);
int test_rw_write_unlock(void);

int plock_acquire(int);
int plock_release(void);

int rw_reader_enter(void);
int rw_reader_exit(void);
int rw_writer_enter(void);
int rw_writer_exit(void);

int stat(const char*, struct stat*);
char* strcpy(char*, const char*);
void *memmove(void*, const void*, int);
char* strchr(const char*, char c);
int strcmp(const char*, const char*);
void printf(int, const char*, ...);
char* gets(char*, int max);
uint strlen(const char*);
void* memset(void*, int, uint);
void* malloc(uint);
void free(void*);
int atoi(const char*);